services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '5173:5173'
    networks:
      - app-network   
networks:
  app-network:
    name: card-them-all-front_app-network
    driver: bridge 