services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile   
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: card-them-all-shared-network
