services:
  frontend:  
    build:
      context: .
      dockerfile: Dockerfile   
    restart: unless-stopped
    networks:
      - app-network
container_name: cardthemall-frontend
networks:
  app-network:
    name: card-them-all-shared-network
