services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network   
networks:
  app-network:
    name: card-them-all-front_app-network
    driver: bridge